import { 
  Faculty, 
  Announcement, 
  Notification, 
  Course, 
  CourseUpdate, 
  Complaint, 
  LostFoundItem, 
  SupportService,
  ComplaintCategory,
  LostFoundCategory,
  CampusEvent,
  EventCategory,
  Opportunity,
  OpportunityCategory,
  StudentOrganization,
  OrganizationCategory,
  EngagementFeedItem
} from './types'

export const faculties: Faculty[] = [
  {
    id: 'agriculture',
    name: 'Faculty of Agriculture',
    departments: [
      { id: 'agric-econ', name: 'Agricultural Economics', facultyId: 'agriculture' },
      { id: 'agric-extension', name: 'Agricultural Extension', facultyId: 'agriculture' },
      { id: 'animal-science', name: 'Animal Science', facultyId: 'agriculture' },
      { id: 'crop-science', name: 'Crop Science', facultyId: 'agriculture' },
      { id: 'soil-science', name: 'Soil Science', facultyId: 'agriculture' },
    ],
  },
  {
    id: 'education',
    name: 'Faculty of Education',
    departments: [
      { id: 'edu-admin', name: 'Educational Administration', facultyId: 'education' },
      { id: 'curriculum', name: 'Curriculum Studies', facultyId: 'education' },
      { id: 'guidance', name: 'Guidance & Counselling', facultyId: 'education' },
      { id: 'edu-tech', name: 'Educational Technology', facultyId: 'education' },
    ],
  },
  {
    id: 'environmental',
    name: 'Faculty of Environmental Sciences',
    departments: [
      { id: 'env-science', name: 'Environmental Science', facultyId: 'environmental' },
      { id: 'forestry', name: 'Forestry', facultyId: 'environmental' },
      { id: 'geography', name: 'Geography', facultyId: 'environmental' },
    ],
  },
  {
    id: 'social',
    name: 'Faculty of Social Sciences',
    departments: [
      { id: 'economics', name: 'Economics', facultyId: 'social' },
      { id: 'mass-comm', name: 'Mass Communication', facultyId: 'social' },
      { id: 'political-science', name: 'Political Science', facultyId: 'social' },
      { id: 'sociology', name: 'Sociology', facultyId: 'social' },
    ],
  },
  {
    id: 'basic-sciences',
    name: 'Faculty of Basic Sciences',
    departments: [
      { id: 'biology', name: 'Biological Sciences', facultyId: 'basic-sciences' },
      { id: 'chemistry', name: 'Chemistry', facultyId: 'basic-sciences' },
      { id: 'mathematics', name: 'Mathematics', facultyId: 'basic-sciences' },
      { id: 'physics', name: 'Physics', facultyId: 'basic-sciences' },
    ],
  },
  {
    id: 'community-health',
    name: 'Faculty of Community Health Sciences',
    departments: [
      { id: 'nursing', name: 'Nursing', facultyId: 'community-health' },
      { id: 'public-health', name: 'Public Health', facultyId: 'community-health' },
      { id: 'clinical-sciences', name: 'Clinical Sciences', facultyId: 'community-health' },
    ],
  },
]

export const yearOfStudyOptions = [
  { value: '1', label: 'Year 1' },
  { value: '2', label: 'Year 2' },
  { value: '3', label: 'Year 3' },
  { value: '4', label: 'Year 4' },
  { value: '5', label: 'Year 5 (Postgraduate)' },
]

// Mock Announcements Data
export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Second Semester Examination Timetable Released',
    content: 'The examination timetable for the second semester 2024/2025 academic year has been released. All students are advised to check the academic portal and departmental notice boards for their specific examination schedules. Ensure you arrive at least 30 minutes before each examination. Any clashes should be reported to the Examinations Office immediately.\n\nImportant Notes:\n- Bring your student ID card to all examinations\n- No electronic devices allowed in examination halls\n- Late arrivals beyond 30 minutes will not be admitted',
    excerpt: 'The examination timetable for the second semester has been released. Check the academic portal for details.',
    author: 'Examinations Office',
    department: 'Academic Registry',
    category: 'exams',
    priority: 'high',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    title: 'Course Registration Deadline Extended',
    content: 'Due to technical difficulties experienced on the student portal, the course registration deadline has been extended by one week. All students who have not completed their registration should do so before the new deadline.\n\nNew Deadline: December 20, 2024\n\nStudents experiencing difficulties should contact the ICT Help Desk or visit the Academic Registry Office.',
    excerpt: 'Course registration deadline extended by one week due to technical issues.',
    author: 'Academic Registry',
    department: 'Academic Registry',
    category: 'registration',
    priority: 'urgent',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: '3',
    title: 'New Scholarship Opportunities for 2025',
    content: 'Applications are now open for the following scholarship programs:\n\n1. Government of Sierra Leone Merit Scholarship\n2. African Development Bank Education Grant\n3. Njala University Vice Chancellor\'s Award\n\nEligible students should submit their applications through the Student Affairs Office. Deadline: January 15, 2025.',
    excerpt: 'Applications open for multiple scholarship programs including Government Merit Scholarship.',
    author: 'Student Affairs',
    department: 'Student Affairs Office',
    category: 'scholarships',
    priority: 'medium',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: '4',
    title: 'Annual Cultural Day Celebration',
    content: 'Join us for the Annual Cultural Day celebration showcasing the rich cultural diversity of Sierra Leone. The event will feature traditional dances, music, fashion shows, and food from all regions.\n\nDate: December 18, 2024\nTime: 10:00 AM - 6:00 PM\nVenue: University Amphitheatre\n\nAll students, staff, and community members are welcome.',
    excerpt: 'Annual Cultural Day celebration featuring traditional dances, music, and food.',
    author: 'Student Union',
    department: 'Student Affairs Office',
    category: 'events',
    priority: 'low',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
  {
    id: '5',
    title: 'Library Operating Hours During Exams',
    content: 'During the examination period, the university library will operate extended hours to support student study needs.\n\nExtended Hours:\n- Monday to Friday: 7:00 AM - 11:00 PM\n- Saturday: 8:00 AM - 10:00 PM\n- Sunday: 9:00 AM - 9:00 PM\n\nThe quiet study areas and computer labs will be available throughout these hours.',
    excerpt: 'Library extends operating hours during examination period.',
    author: 'University Librarian',
    department: 'Library Services',
    category: 'general',
    priority: 'medium',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
  },
  {
    id: '6',
    title: 'Important: Student ID Card Collection',
    content: 'All first-year students who have completed their registration are required to collect their student ID cards from the Student Affairs Office.\n\nRequirements:\n- Receipt of payment\n- Admission letter\n- Two passport photographs\n\nCollection Hours: 9:00 AM - 4:00 PM (Monday - Friday)',
    excerpt: 'First-year students to collect ID cards from Student Affairs Office.',
    author: 'Student Affairs',
    department: 'Student Affairs Office',
    category: 'registration',
    priority: 'medium',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000),
  },
]

// Mock Notifications Data
export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'CSC 201 Assignment Deadline Updated',
    message: 'The deadline for Database Systems assignment has been extended to December 15th.',
    type: 'academic',
    read: false,
    userId: 'user-1',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: '2',
    title: 'Registration Closes in 2 Days',
    message: 'Complete your course registration before the deadline to avoid late fees.',
    type: 'administrative',
    read: false,
    userId: 'user-1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '3',
    title: 'Innovation Workshop Tomorrow',
    message: 'Don\'t miss the Tech Innovation Workshop at the Main Hall, 2:00 PM.',
    type: 'event',
    read: false,
    userId: 'user-1',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: '4',
    title: 'New Scholarship Opportunity',
    message: 'African Development Bank scholarship applications are now open.',
    type: 'scholarship',
    read: true,
    userId: 'user-1',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: '5',
    title: 'Profile Verification Complete',
    message: 'Your student profile has been verified successfully.',
    type: 'system',
    read: true,
    userId: 'user-1',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
  {
    id: '6',
    title: 'New Course Material Available',
    message: 'Lecture slides for MAT 201 Week 10 have been uploaded.',
    type: 'academic',
    read: true,
    userId: 'user-1',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
  },
]

// Mock Courses Data
export const mockCourses: Course[] = [
  {
    id: 'csc201',
    code: 'CSC 201',
    title: 'Database Systems',
    lecturer: 'Dr. Mohamed Kamara',
    credits: 3,
    updateCount: 3,
  },
  {
    id: 'mat201',
    code: 'MAT 201',
    title: 'Linear Algebra',
    lecturer: 'Prof. Fatmata Bangura',
    credits: 3,
    updateCount: 2,
  },
  {
    id: 'csc202',
    code: 'CSC 202',
    title: 'Data Structures & Algorithms',
    lecturer: 'Dr. Ibrahim Sesay',
    credits: 4,
    updateCount: 5,
  },
  {
    id: 'eng201',
    code: 'ENG 201',
    title: 'Technical Writing',
    lecturer: 'Mrs. Mariama Conteh',
    credits: 2,
    updateCount: 1,
  },
  {
    id: 'phy201',
    code: 'PHY 201',
    title: 'Electricity & Magnetism',
    lecturer: 'Dr. Samuel Koroma',
    credits: 3,
    updateCount: 0,
  },
]

// Mock Course Updates Data
export const mockCourseUpdates: CourseUpdate[] = [
  {
    id: 'u1',
    courseId: 'csc201',
    type: 'assignment',
    title: 'Assignment 3: SQL Queries',
    description: 'Complete the SQL query exercises on normalization and joins.',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'u2',
    courseId: 'csc201',
    type: 'material',
    title: 'Lecture Slides: Week 12',
    description: 'Database indexing and query optimization slides uploaded.',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'u3',
    courseId: 'csc201',
    type: 'announcement',
    title: 'Class Rescheduled',
    description: 'Friday class moved to Monday 10:00 AM in Room LT3.',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
  {
    id: 'u4',
    courseId: 'mat201',
    type: 'quiz',
    title: 'Quiz 4: Eigenvalues',
    description: 'Online quiz on eigenvalues and eigenvectors.',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: 'u5',
    courseId: 'mat201',
    type: 'material',
    title: 'Practice Problems Set 8',
    description: 'Additional practice problems for matrix operations.',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
  },
  {
    id: 'u6',
    courseId: 'csc202',
    type: 'assignment',
    title: 'Project: Binary Search Tree Implementation',
    description: 'Implement a BST with insert, delete, and search operations.',
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'u7',
    courseId: 'csc202',
    type: 'schedule',
    title: 'Lab Session Change',
    description: 'Lab sessions now on Wednesdays 2-5 PM in Computer Lab 2.',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'u8',
    courseId: 'eng201',
    type: 'material',
    title: 'Report Writing Guidelines',
    description: 'Updated guidelines for technical report formatting.',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000),
  },
]

// Announcement categories for tabs
export const announcementCategories = [
  { id: 'all', label: 'All' },
  { id: 'exams', label: 'Exams' },
  { id: 'registration', label: 'Registration' },
  { id: 'scholarships', label: 'Scholarships' },
  { id: 'events', label: 'Events' },
  { id: 'general', label: 'General' },
] as const

// Notification type labels
export const notificationTypes = [
  { id: 'all', label: 'All' },
  { id: 'academic', label: 'Academic' },
  { id: 'administrative', label: 'Administrative' },
  { id: 'event', label: 'Events' },
  { id: 'scholarship', label: 'Scholarships' },
  { id: 'system', label: 'System' },
] as const

// Complaint categories with metadata
export const complaintCategories: { id: ComplaintCategory; label: string; description: string; icon: string }[] = [
  { id: 'hostel', label: 'Hostel Issues', description: 'Room, furniture, or accommodation problems', icon: 'building' },
  { id: 'electricity', label: 'Electricity Problems', description: 'Power outages, faulty wiring, or lighting', icon: 'zap' },
  { id: 'water', label: 'Water Supply', description: 'Water shortage, plumbing, or drainage issues', icon: 'droplets' },
  { id: 'internet', label: 'Internet/Network', description: 'WiFi, connectivity, or network problems', icon: 'wifi' },
  { id: 'academic', label: 'Academic Issues', description: 'Course, grades, or lecturer concerns', icon: 'graduation-cap' },
  { id: 'security', label: 'Security Concerns', description: 'Safety, theft, or security incidents', icon: 'shield' },
]

// Lost & Found categories
export const lostFoundCategories: { id: LostFoundCategory; label: string }[] = [
  { id: 'student-id', label: 'Student ID' },
  { id: 'phone', label: 'Phone' },
  { id: 'wallet', label: 'Wallet' },
  { id: 'laptop', label: 'Laptop' },
  { id: 'books', label: 'Books' },
  { id: 'keys', label: 'Keys' },
  { id: 'others', label: 'Others' },
]

// Mock user for complaints/lost-found
const mockUser = {
  id: 'user-1',
  fullName: 'Fatmata Kamara',
  email: 'fatmata.kamara@njala.edu.sl',
  role: 'student' as const,
  studentId: 'NJU/2022/0456',
  faculty: 'basic-sciences',
  department: 'mathematics',
  yearOfStudy: 3,
  createdAt: new Date(),
  updatedAt: new Date(),
}

// Mock Complaints Data
export const mockComplaints: Complaint[] = [
  {
    id: 'c1',
    title: 'No Water in Block A Hostel',
    description: 'There has been no water supply in Block A for the past 3 days. Students are struggling to maintain hygiene. This is urgent and needs immediate attention.',
    category: 'water',
    status: 'in-progress',
    priority: 'urgent',
    location: 'Block A Hostel, Njala Campus',
    submittedBy: mockUser,
    assignedTo: 'Maintenance Team',
    timeline: [
      {
        id: 't1',
        complaintId: 'c1',
        status: 'pending',
        message: 'Complaint submitted',
        updatedBy: 'System',
        createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
      },
      {
        id: 't2',
        complaintId: 'c1',
        status: 'in-progress',
        message: 'Issue assigned to maintenance team. Plumber will inspect the water tank.',
        updatedBy: 'Admin',
        createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
  {
    id: 'c2',
    title: 'WiFi Not Working in Library',
    description: 'The WiFi connection in the university library has been extremely slow and keeps disconnecting. This is affecting our ability to do research.',
    category: 'internet',
    status: 'pending',
    priority: 'high',
    location: 'University Library',
    submittedBy: mockUser,
    timeline: [
      {
        id: 't3',
        complaintId: 'c2',
        status: 'pending',
        message: 'Complaint submitted',
        updatedBy: 'System',
        createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'c3',
    title: 'Broken Window in Room 205',
    description: 'The window in my room has been broken and needs replacement. It poses a security risk and lets in rain during storms.',
    category: 'hostel',
    status: 'resolved',
    priority: 'medium',
    location: 'Block B, Room 205',
    submittedBy: mockUser,
    assignedTo: 'Hostel Administrator',
    timeline: [
      {
        id: 't4',
        complaintId: 'c3',
        status: 'pending',
        message: 'Complaint submitted',
        updatedBy: 'System',
        createdAt: new Date(Date.now() - 168 * 60 * 60 * 1000),
      },
      {
        id: 't5',
        complaintId: 'c3',
        status: 'in-progress',
        message: 'Maintenance scheduled for inspection',
        updatedBy: 'Hostel Admin',
        createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000),
      },
      {
        id: 't6',
        complaintId: 'c3',
        status: 'resolved',
        message: 'Window replaced successfully. Issue resolved.',
        updatedBy: 'Maintenance Team',
        createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 168 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
  {
    id: 'c4',
    title: 'Streetlights Not Working',
    description: 'Multiple streetlights along the path from the hostels to the main campus are not functioning. This is a safety concern especially for late-night classes.',
    category: 'electricity',
    status: 'pending',
    priority: 'high',
    location: 'Hostel to Campus Pathway',
    submittedBy: mockUser,
    timeline: [
      {
        id: 't7',
        complaintId: 'c4',
        status: 'pending',
        message: 'Complaint submitted',
        updatedBy: 'System',
        createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
]

// Mock Lost & Found Data
export const mockLostItems: LostFoundItem[] = [
  {
    id: 'l1',
    title: 'Student ID Card - Mohamed S.',
    description: 'Blue Njala University student ID card. Name: Mohamed Sesay. Department of Agriculture.',
    type: 'lost',
    category: 'student-id',
    location: 'Main Library',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    contactInfo: '076-123-4567',
    status: 'active',
    submittedBy: mockUser,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'l2',
    title: 'Black Samsung Phone',
    description: 'Samsung Galaxy A54 with cracked screen protector. Has a blue phone case.',
    type: 'lost',
    category: 'phone',
    location: 'Lecture Hall 2',
    date: new Date(Date.now() - 48 * 60 * 60 * 1000),
    contactInfo: '078-987-6543',
    status: 'active',
    submittedBy: mockUser,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
  {
    id: 'l3',
    title: 'Brown Leather Wallet',
    description: 'Small brown leather wallet containing student ID and some cash. Lost near cafeteria.',
    type: 'lost',
    category: 'wallet',
    location: 'University Cafeteria',
    date: new Date(Date.now() - 72 * 60 * 60 * 1000),
    contactInfo: '077-456-7890',
    status: 'claimed',
    submittedBy: mockUser,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
  },
]

export const mockFoundItems: LostFoundItem[] = [
  {
    id: 'f1',
    title: 'Set of Keys with Blue Keychain',
    description: 'Found a set of 3 keys with a blue Njala University keychain near the admin building.',
    type: 'found',
    category: 'keys',
    location: 'Administration Building',
    date: new Date(Date.now() - 6 * 60 * 60 * 1000),
    contactInfo: 'Student Affairs Office',
    status: 'active',
    submittedBy: mockUser,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'f2',
    title: 'HP Laptop Charger',
    description: 'Black HP laptop charger found in Computer Lab 1. 65W power adapter.',
    type: 'found',
    category: 'laptop',
    location: 'Computer Lab 1',
    date: new Date(Date.now() - 12 * 60 * 60 * 1000),
    contactInfo: 'ICT Help Desk',
    status: 'active',
    submittedBy: mockUser,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: 'f3',
    title: 'Introduction to Programming Textbook',
    description: 'CSC 101 textbook found in Lecture Hall 3. Has name written inside cover.',
    type: 'found',
    category: 'books',
    location: 'Lecture Hall 3',
    date: new Date(Date.now() - 36 * 60 * 60 * 1000),
    contactInfo: '076-555-1234',
    status: 'resolved',
    submittedBy: mockUser,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
  },
]

// Support Services
export const supportServices: SupportService[] = [
  {
    id: 'ict',
    name: 'ICT Support',
    description: 'Technical support for internet, email, and computer issues',
    icon: 'monitor',
    contactPhone: '076-ICT-HELP',
    contactEmail: 'ict@njala.edu.sl',
    location: 'ICT Building, Ground Floor',
    hours: 'Mon-Fri: 8:00 AM - 5:00 PM',
  },
  {
    id: 'hostel',
    name: 'Hostel Administration',
    description: 'Accommodation, room allocation, and hostel-related concerns',
    icon: 'building',
    contactPhone: '076-HOST-001',
    contactEmail: 'hostel@njala.edu.sl',
    location: 'Student Affairs Building',
    hours: 'Mon-Fri: 9:00 AM - 4:00 PM',
  },
  {
    id: 'student-affairs',
    name: 'Student Affairs',
    description: 'Student welfare, counseling, and general student services',
    icon: 'users',
    contactPhone: '076-STU-AFRS',
    contactEmail: 'studentaffairs@njala.edu.sl',
    location: 'Administration Block, 2nd Floor',
    hours: 'Mon-Fri: 8:00 AM - 4:00 PM',
  },
  {
    id: 'academic',
    name: 'Academic Affairs',
    description: 'Course registration, transcripts, and academic records',
    icon: 'graduation-cap',
    contactPhone: '076-ACA-DMCS',
    contactEmail: 'academics@njala.edu.sl',
    location: 'Academic Registry Building',
    hours: 'Mon-Fri: 9:00 AM - 3:00 PM',
  },
  {
    id: 'security',
    name: 'Security Office',
    description: 'Campus safety, incident reporting, and emergency assistance',
    icon: 'shield',
    contactPhone: '076-SEC-RITY',
    contactEmail: 'security@njala.edu.sl',
    location: 'Main Gate Security Post',
    hours: '24/7 Available',
  },
  {
    id: 'health',
    name: 'Health Center',
    description: 'Medical services, health consultations, and first aid',
    icon: 'heart-pulse',
    contactPhone: '076-HEL-THCR',
    contactEmail: 'health@njala.edu.sl',
    location: 'Campus Health Center',
    hours: 'Mon-Sat: 8:00 AM - 8:00 PM',
  },
]

// Priority levels for complaints
export const priorityLevels = [
  { id: 'low', label: 'Low', description: 'Minor issue, no urgency' },
  { id: 'medium', label: 'Medium', description: 'Moderate impact, can wait' },
  { id: 'high', label: 'High', description: 'Significant impact, needs attention' },
  { id: 'urgent', label: 'Urgent', description: 'Critical issue, immediate action required' },
] as const

// ==================== PHASE 4: Events, Opportunities, Organizations ====================

// Event categories with metadata
export const eventCategories: { id: EventCategory; label: string; description: string }[] = [
  { id: 'academic', label: 'Academic', description: 'Lectures, seminars, and workshops' },
  { id: 'innovation', label: 'Innovation', description: 'Tech talks, hackathons, and demos' },
  { id: 'student-org', label: 'Student Organization', description: 'Club meetings and activities' },
  { id: 'sports', label: 'Sports', description: 'Games, tournaments, and fitness' },
  { id: 'religious', label: 'Religious', description: 'Faith-based gatherings' },
  { id: 'entertainment', label: 'Entertainment', description: 'Concerts, shows, and fun events' },
  { id: 'career', label: 'Career', description: 'Job fairs and career development' },
  { id: 'community', label: 'Community Service', description: 'Volunteering and outreach' },
]

// Opportunity categories
export const opportunityCategories: { id: OpportunityCategory; label: string }[] = [
  { id: 'scholarship', label: 'Scholarships' },
  { id: 'internship', label: 'Internships' },
  { id: 'hackathon', label: 'Hackathons' },
  { id: 'training', label: 'Trainings' },
  { id: 'job', label: 'Jobs' },
  { id: 'grant', label: 'Grants' },
  { id: 'fellowship', label: 'Fellowships' },
  { id: 'competition', label: 'Competitions' },
]

// Organization categories
export const organizationCategories: { id: OrganizationCategory; label: string }[] = [
  { id: 'academic-society', label: 'Academic Society' },
  { id: 'innovation-club', label: 'Innovation Club' },
  { id: 'religious-group', label: 'Religious Group' },
  { id: 'sports-club', label: 'Sports Club' },
  { id: 'cultural-group', label: 'Cultural Group' },
  { id: 'volunteer-group', label: 'Volunteer Group' },
]

// Mock Campus Events
export const mockEvents: CampusEvent[] = [
  {
    id: 'evt1',
    title: 'Tech Innovation Workshop 2025',
    description: 'Join us for an exciting workshop on emerging technologies including AI, blockchain, and IoT. Learn from industry experts and get hands-on experience building real-world projects. This workshop is open to all students interested in technology and innovation.',
    shortDescription: 'Learn AI, blockchain, and IoT from industry experts with hands-on projects.',
    category: 'innovation',
    imageUrl: '/images/events/tech-workshop.jpg',
    location: 'Computer Science Building, Room 101',
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000),
    organizer: 'Innovation Club',
    organizerId: 'org1',
    contactPerson: 'Ibrahim Sesay',
    contactEmail: 'innovation@njala.edu.sl',
    contactPhone: '076-123-4567',
    agenda: [
      { time: '09:00 AM', title: 'Registration & Welcome', description: 'Check-in and refreshments' },
      { time: '09:30 AM', title: 'Introduction to AI', description: 'Overview of artificial intelligence concepts' },
      { time: '11:00 AM', title: 'Hands-on Workshop', description: 'Build your first AI model' },
      { time: '01:00 PM', title: 'Lunch Break' },
      { time: '02:00 PM', title: 'Blockchain Fundamentals', description: 'Understanding decentralized systems' },
      { time: '04:00 PM', title: 'Closing & Networking' },
    ],
    rsvpCount: 87,
    savedCount: 45,
    isFeatured: true,
    status: 'upcoming',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'evt2',
    title: 'Career Fair 2025',
    description: 'Connect with top employers from Sierra Leone and beyond. Bring your CV and be ready for on-the-spot interviews. Companies from banking, agriculture, technology, and NGO sectors will be present.',
    shortDescription: 'Meet employers from banking, agriculture, tech, and NGOs. Bring your CV!',
    category: 'career',
    imageUrl: '/images/events/career-fair.jpg',
    location: 'University Amphitheatre',
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000),
    organizer: 'Student Affairs Office',
    contactPerson: 'Mrs. Fatmata Bangura',
    contactEmail: 'careers@njala.edu.sl',
    agenda: [
      { time: '09:00 AM', title: 'Opening Ceremony' },
      { time: '10:00 AM', title: 'Company Booths Open' },
      { time: '02:00 PM', title: 'Panel Discussion: Future of Work' },
      { time: '04:00 PM', title: 'Networking Session' },
    ],
    rsvpCount: 234,
    savedCount: 120,
    isFeatured: true,
    status: 'upcoming',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'evt3',
    title: 'Inter-Faculty Football Tournament',
    description: 'The annual inter-faculty football tournament kicks off! Come support your faculty team as they compete for the championship trophy. Matches every weekend.',
    shortDescription: 'Support your faculty team in the annual football championship!',
    category: 'sports',
    imageUrl: '/images/events/football.jpg',
    location: 'University Sports Ground',
    startDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    organizer: 'Sports Committee',
    contactPerson: 'Mr. Samuel Koroma',
    contactEmail: 'sports@njala.edu.sl',
    rsvpCount: 156,
    savedCount: 89,
    isFeatured: false,
    status: 'upcoming',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'evt4',
    title: 'Friday Prayer Service',
    description: 'Weekly Friday prayer service for all Muslim students and staff. Join us for prayers and fellowship.',
    shortDescription: 'Weekly Friday prayers for Muslim students and staff.',
    category: 'religious',
    location: 'University Mosque',
    startDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
    organizer: 'Muslim Students Association',
    organizerId: 'org3',
    contactPerson: 'Alhaji Mohamed Kamara',
    rsvpCount: 78,
    savedCount: 23,
    status: 'upcoming',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'evt5',
    title: 'Cultural Night: Celebrating Sierra Leone',
    description: 'An evening celebrating the rich cultural diversity of Sierra Leone. Featuring traditional dances, music, poetry, and food from all regions. Dress in your traditional attire!',
    shortDescription: 'Traditional dances, music, poetry, and food from all regions of Sierra Leone.',
    category: 'entertainment',
    imageUrl: '/images/events/cultural-night.jpg',
    location: 'University Amphitheatre',
    startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 5 * 60 * 60 * 1000),
    organizer: 'Cultural Society',
    organizerId: 'org5',
    contactPerson: 'Mariama Conteh',
    contactEmail: 'culture@njala.edu.sl',
    rsvpCount: 312,
    savedCount: 178,
    isFeatured: true,
    status: 'upcoming',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'evt6',
    title: 'Research Methodology Seminar',
    description: 'A comprehensive seminar on research methodology for final year students. Learn about proposal writing, data collection, and analysis techniques.',
    shortDescription: 'Research methodology for final year students - proposals, data, analysis.',
    category: 'academic',
    location: 'Lecture Hall 1',
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000),
    organizer: 'Academic Affairs',
    contactPerson: 'Dr. Mohamed Kamara',
    contactEmail: 'academics@njala.edu.sl',
    rsvpCount: 145,
    savedCount: 67,
    status: 'upcoming',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'evt7',
    title: 'Campus Clean-Up Day',
    description: 'Join fellow students in making our campus beautiful. Volunteer for the monthly campus clean-up initiative. Refreshments provided!',
    shortDescription: 'Monthly volunteer initiative to clean and beautify our campus.',
    category: 'community',
    location: 'Meet at Main Gate',
    startDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000),
    organizer: 'Green Campus Initiative',
    organizerId: 'org6',
    contactPerson: 'Amina Bangura',
    rsvpCount: 56,
    savedCount: 34,
    status: 'upcoming',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
]

// Mock Opportunities
export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp1',
    title: 'Government of Sierra Leone Merit Scholarship 2025',
    description: 'Full scholarship for outstanding students in STEM fields. Covers tuition, accommodation, and monthly stipend. Open to Year 2 and Year 3 students with CGPA of 3.5 and above.',
    shortDescription: 'Full scholarship for STEM students with CGPA 3.5+. Tuition, accommodation, and stipend included.',
    category: 'scholarship',
    provider: 'Ministry of Technical & Higher Education',
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    eligibility: [
      'Sierra Leonean citizen',
      'Year 2 or Year 3 student',
      'CGPA of 3.5 and above',
      'Enrolled in STEM program',
    ],
    requirements: [
      'Academic transcripts',
      'Letter of recommendation from HOD',
      'Personal statement (500 words)',
      'Proof of citizenship',
    ],
    benefits: [
      'Full tuition coverage',
      'Accommodation allowance',
      'Monthly stipend of Le 500,000',
      'Book allowance',
    ],
    applicationLink: 'https://mthe.gov.sl/scholarships',
    status: 'open',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp2',
    title: 'Orange Digital Center Internship Program',
    description: 'Three-month paid internship at Orange Sierra Leone. Gain practical experience in telecommunications, IT support, and digital marketing. Perfect for ICT and Business students.',
    shortDescription: 'Paid 3-month internship at Orange SL. ICT and Business students welcome.',
    category: 'internship',
    provider: 'Orange Sierra Leone',
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    eligibility: [
      'Final year student or recent graduate',
      'ICT, Business, or Marketing major',
      'Basic computer skills',
    ],
    requirements: [
      'Updated CV',
      'Cover letter',
      'Academic transcript',
    ],
    benefits: [
      'Monthly stipend',
      'Professional training',
      'Certificate of completion',
      'Potential full-time employment',
    ],
    applicationLink: 'https://orange.sl/careers',
    status: 'closing-soon',
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp3',
    title: 'Africa Code Week Hackathon 2025',
    description: 'Join the biggest coding competition in Africa! Build solutions for local challenges using technology. Cash prizes and internship opportunities for winners.',
    shortDescription: 'Biggest coding competition in Africa with cash prizes and internship opportunities.',
    category: 'hackathon',
    provider: 'SAP & UNESCO',
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
    eligibility: [
      'University student in Africa',
      'Basic programming knowledge',
      'Team of 2-5 members',
    ],
    requirements: [
      'Team registration',
      'Project proposal',
      'Student ID',
    ],
    benefits: [
      'First prize: $5,000',
      'Second prize: $3,000',
      'Third prize: $1,500',
      'SAP internship opportunities',
    ],
    applicationLink: 'https://africacodeweek.org/hackathon',
    status: 'open',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp4',
    title: 'Digital Skills Training by UNDP',
    description: 'Free comprehensive training in digital marketing, web development, and data analysis. Certificate provided upon completion. Limited slots available!',
    shortDescription: 'Free training in digital marketing, web dev, and data analysis. Certificate provided.',
    category: 'training',
    provider: 'UNDP Sierra Leone',
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    eligibility: [
      'Youth aged 18-35',
      'Basic computer literacy',
      'Commitment to complete 6-week program',
    ],
    requirements: [
      'Application form',
      'National ID',
      'Motivation letter',
    ],
    benefits: [
      'Free training',
      'Certificate',
      'Laptop provided during training',
      'Job placement support',
    ],
    applicationLink: 'https://undp.org/sierraleone/digitalskills',
    status: 'open',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp5',
    title: 'Graduate Trainee - Sierra Leone Commercial Bank',
    description: 'Join our graduate trainee program and kickstart your career in banking. 18-month rotational program across all departments.',
    shortDescription: '18-month rotational graduate program in all banking departments.',
    category: 'job',
    provider: 'Sierra Leone Commercial Bank',
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    eligibility: [
      'Recent graduate (within 2 years)',
      'Degree in Business, Economics, or related field',
      'Minimum of Second Class Upper',
    ],
    requirements: [
      'CV and cover letter',
      'Academic certificates',
      'NASSIT number',
      'Two referees',
    ],
    benefits: [
      'Competitive salary',
      'Health insurance',
      'Training and development',
      'Clear career progression',
    ],
    applicationLink: 'https://slcb.sl/careers',
    status: 'closing-soon',
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'opp6',
    title: 'Mastercard Foundation Scholars Program',
    description: 'Full scholarship for postgraduate studies at partner universities in Africa. Leadership development and career support included.',
    shortDescription: 'Full postgraduate scholarship with leadership development and career support.',
    category: 'fellowship',
    provider: 'Mastercard Foundation',
    deadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    eligibility: [
      'African citizen',
      'Demonstrated academic excellence',
      'Commitment to giving back to community',
      'Financial need',
    ],
    requirements: [
      'Online application',
      'Academic transcripts',
      'Personal essays',
      'Letters of recommendation',
    ],
    benefits: [
      'Full tuition',
      'Living expenses',
      'Travel costs',
      'Leadership development',
    ],
    applicationLink: 'https://mastercardfdn.org/scholars',
    status: 'closed',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
  },
]

// Mock Student Organizations
export const mockOrganizations: StudentOrganization[] = [
  {
    id: 'org1',
    name: 'Njala Innovation Club',
    description: 'A community of tech enthusiasts, developers, and innovators building solutions for local challenges. We organize hackathons, coding bootcamps, and tech talks.',
    mission: 'To foster a culture of innovation and technology among Njala students.',
    category: 'innovation-club',
    logoUrl: '/images/orgs/innovation-club.jpg',
    memberCount: 156,
    leaders: [
      { name: 'Ibrahim Sesay', role: 'President' },
      { name: 'Fatmata Koroma', role: 'Vice President' },
      { name: 'Mohamed Bangura', role: 'Secretary' },
    ],
    contactPerson: 'Ibrahim Sesay',
    contactEmail: 'innovation@njala.edu.sl',
    contactPhone: '076-123-4567',
    meetingSchedule: 'Every Saturday, 2:00 PM',
    location: 'Computer Science Building, Room 101',
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'org2',
    name: 'Njala Mathematics Society',
    description: 'Promoting mathematical excellence through tutorials, competitions, and collaborative learning. Open to all students passionate about mathematics.',
    mission: 'To make mathematics accessible and enjoyable for all students.',
    category: 'academic-society',
    memberCount: 89,
    leaders: [
      { name: 'Dr. Fatmata Bangura', role: 'Patron' },
      { name: 'Samuel Kamara', role: 'President' },
      { name: 'Amina Sesay', role: 'Secretary' },
    ],
    contactPerson: 'Samuel Kamara',
    contactEmail: 'mathsociety@njala.edu.sl',
    meetingSchedule: 'Every Wednesday, 4:00 PM',
    location: 'Mathematics Department',
    createdAt: new Date(Date.now() - 730 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'org3',
    name: 'Muslim Students Association',
    description: 'Uniting Muslim students in faith, fellowship, and service. We organize prayers, lectures, charity drives, and interfaith dialogues.',
    mission: 'To nurture the spiritual growth of Muslim students while promoting peace and understanding.',
    category: 'religious-group',
    memberCount: 234,
    leaders: [
      { name: 'Alhaji Mohamed Kamara', role: 'Amir' },
      { name: 'Haja Mariama Conteh', role: 'Amira' },
      { name: 'Sheikh Ibrahim Turay', role: 'Spiritual Advisor' },
    ],
    contactPerson: 'Alhaji Mohamed Kamara',
    contactPhone: '077-456-7890',
    meetingSchedule: 'Friday prayers at 1:00 PM',
    location: 'University Mosque',
    createdAt: new Date(Date.now() - 1095 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'org4',
    name: 'Njala Lions Football Club',
    description: 'The official football club of Njala University. We train, compete, and promote sportsmanship. Trials open to all students.',
    mission: 'To develop athletic talent and represent Njala in inter-university competitions.',
    category: 'sports-club',
    memberCount: 45,
    leaders: [
      { name: 'Mr. Samuel Koroma', role: 'Coach' },
      { name: 'Alpha Bangura', role: 'Captain' },
      { name: 'Ibrahim Jalloh', role: 'Vice Captain' },
    ],
    contactPerson: 'Alpha Bangura',
    contactEmail: 'football@njala.edu.sl',
    meetingSchedule: 'Training: Mon, Wed, Fri at 4:00 PM',
    location: 'University Sports Ground',
    createdAt: new Date(Date.now() - 1460 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'org5',
    name: 'Cultural Heritage Society',
    description: 'Preserving and celebrating Sierra Leonean culture through dance, music, drama, and storytelling. We organize cultural nights and heritage tours.',
    mission: 'To preserve and promote the rich cultural heritage of Sierra Leone among students.',
    category: 'cultural-group',
    memberCount: 78,
    leaders: [
      { name: 'Mariama Conteh', role: 'President' },
      { name: 'Isatu Kamara', role: 'Vice President' },
      { name: 'Foday Sesay', role: 'Cultural Director' },
    ],
    contactPerson: 'Mariama Conteh',
    contactEmail: 'culture@njala.edu.sl',
    meetingSchedule: 'Every Thursday, 5:00 PM',
    location: 'Student Union Building',
    createdAt: new Date(Date.now() - 548 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'org6',
    name: 'Green Campus Initiative',
    description: 'Environmental advocacy and action on campus. We organize clean-ups, tree planting, and awareness campaigns about climate change.',
    mission: 'To make Njala University a model of environmental sustainability.',
    category: 'volunteer-group',
    memberCount: 67,
    leaders: [
      { name: 'Amina Bangura', role: 'Coordinator' },
      { name: 'Mohamed Turay', role: 'Projects Lead' },
      { name: 'Fatmata Jalloh', role: 'Outreach Lead' },
    ],
    contactPerson: 'Amina Bangura',
    contactEmail: 'greencampus@njala.edu.sl',
    meetingSchedule: 'Every Saturday, 8:00 AM',
    location: 'Environmental Science Building',
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000),
  },
]

// Mock Engagement Feed
export const mockEngagementFeed: EngagementFeedItem[] = [
  {
    id: 'feed1',
    type: 'event',
    title: 'Tech Innovation Workshop 2025 is tomorrow!',
    description: 'Last chance to RSVP for the biggest tech event of the semester.',
    actionUrl: '/events/evt1',
    actionLabel: 'View Event',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'feed2',
    type: 'opportunity',
    title: 'Orange Internship deadline in 7 days',
    description: 'Applications closing soon for the paid internship program.',
    actionUrl: '/opportunities/opp2',
    actionLabel: 'Apply Now',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: 'feed3',
    type: 'organization',
    title: 'Innovation Club membership drive',
    description: 'Join Njala Innovation Club and be part of the tech revolution!',
    actionUrl: '/organizations/org1',
    actionLabel: 'Join Now',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 'feed4',
    type: 'event',
    title: 'Career Fair 2025 registration open',
    description: '50+ companies confirmed. Prepare your CV and register now.',
    actionUrl: '/events/evt2',
    actionLabel: 'Register',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: 'feed5',
    type: 'announcement',
    title: 'Cultural Night tickets available',
    description: 'Limited seats for the biggest cultural celebration of the year.',
    actionUrl: '/events/evt5',
    actionLabel: 'Get Tickets',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
]
